# more on http://wiki.ros.org/navigation/Tutorials/RobotSetup

# The "static_map" parameter determines whether or not the costmap should initialize itself 
# based on a map served by the map_server. If you aren't using an existing map or map server, 
# set the static_map parameter to false.

global_costmap:
  global_frame: world
  robot_base_frame: base
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
    
  plugins:
    - 
     name: obstacle_layer
     type: "costmap_2d::ObstacleLayer"  
    -
     name: inflation_layer
     type: "costmap_2d::InflationLayer"
    -
     name: traversability_layer
     type: "costmap_2d::TraversabilityLayer"

  virtual_obstacles:
    observation_sources: laser_scan_sensor
    
  obstacle_layer:
    enabled: true
    observation_sources: laser_scan_sensor 
    laser_scan_sensor:
      data_type: 'LaserScan'
      topic: scan
      marking: true
      clearing: true
      min_obstacle_height: -100.0
      max_obstacle_height: 100.0
      observation_persistence: 0.4
      inf_is_valid: true   

  inflation_layer:
    enabled: true
    observation_sources: laser_scan_sensor
    
# The configuration down here has to be used if you want to use a single static
# layer. Remember also to uncomment the node gridmap_converter_node in 
# traversability_mapping.launch
#
# global_costmap:
#   global_frame: world
#   robot_base_frame: base
#   update_frequency: 5.0
#   publish_frequency: 2.0
#   
#   static_map: false
#   map_topic: /traversability_occ_map
#   
#   plugins:
#     -
#      name: static
#      type: "costmap_2d::StaticLayer"
    
