# more on http://wiki.ros.org/navigation/Tutorials/RobotSetup

# The "static_map" parameter determines whether or not the costmap should initialize itself 
# based on a map served by the map_server. If you aren't using an existing map or map server, 
# set the static_map parameter to false.

global_costmap:
  update_frequency: 5.0
  publish_frequency: 2.0
  rolling_window: true
  static_map: false

  plugins:
    - 
     name: obstacle_layer
     type: "costmap_2d::ObstacleLayer"  
    -
     name: inflation_layer
     type: "costmap_2d::InflationLayer"


  virtual_obstacles:
    observation_sources: laser_scan_sensor
    
  obstacle_layer:
    enabled: true
    observation_sources: laser_scan_sensor 
    laser_scan_sensor:
      data_type: 'LaserScan'
      topic: scan
      marking: true
      clearing: true
      min_obstacle_height: -100.0
      max_obstacle_height: 100.0
      observation_persistence: 0.4
      inf_is_valid: true

  inflation_layer:
    enabled: true
    inflation_radius: 0.4
    observation_sources: laser_scan_sensor 
   
