# more on http://wiki.ros.org/navigation/Tutorials/RobotSetup

# The "static_map" parameter determines whether or not the costmap should initialize itself 
# based on a map served by the map_server. If you aren't using an existing map or map server, 
# set the static_map parameter to false.

global_costmap:
  global_frame: world
  robot_base_frame: base
  update_frequency: 5.0
  publish_frequency: 2.0
  
  static_map: false
  rolling_window: true # Map moves with robot
  map_topic: /traversability_occ_map

  plugins:
    - 
      name: static
      type: "costmap_2d::StaticLayer"

#### OMPL Planner Parameters ####
OmplPlanner:
  use_distance_threshold: true
  simplify_solution: true
  trust_approx_solution: false
  verbose_planner: false
  
  distance_threshold: 1.05     # [m]
  goal_bias: 0.05
  robot_radius: 0.45           # [m]
  num_seconds_to_plan: 2.5     # [s]
  min_distance_waypoints: 3.0  # [m]
  dist_goal_reached: 0.3       # [m] Threshold to consider the goal reached

  planner_type: 1 # 0: RRT Connect, 1: RRT*, 2: PRM
  replanning_rate: 5.0 # [Hz]
  
  odometry_topic: "/camera/odom/sample"

 
   
