# more on http://wiki.ros.org/navigation/Tutorials/RobotSetup

global_costmap:
  update_frequency: 5.0
  publish_frequency: 2.0
  
  resolution: 0.4
  inflation_radius: 0.4

  plugins:
    - 
     name: obstacle_layer
     type: "costmap_2d::ObstacleLayer"  
    -
     name: inflation_layer
     type: "costmap_2d::InflationLayer"

  virtual_obstacles:
    observation_sources: laser_scan_sensor
    
  obstacle_layer:
    enabled: true
    observation_sources: laser_scan_sensor 
    laser_scan_sensor:
      data_type: 'LaserScan'
      topic: scan
      marking: true
      clearing: true
      min_obstacle_height: -100.0
      max_obstacle_height: 100.0
      observation_persistence: 0.4
      inf_is_valid: true   

  inflation_layer:
    enabled: true
    observation_sources: laser_scan_sensor

#### OMPL Planner Parameters ####
OmplPlanner:
  use_distance_threshold: true
  simplify_solution: false       # If 'true', some nodes in the path will be pruned
  trust_approx_solution: false
  verbose_planner: false
  enable_timer_collisions: false # If 'true', the global planner will check for collision at 'replanning rate' and will replan if in collision
  
  distance_threshold: 1.10     # [m]
  goal_bias: 0.05              # [m]
  tree_range: 1.0             # [%] Increase this to have longer branches in the RRT path (in sim: 0.1, in real: 0.3)
  robot_radius: 0.50           # [m]
  interpolation_factor: 0.10   # [-]
  num_seconds_to_plan: 10.0     # [s]
  min_distance_waypoints: 0.05 # [m]
  dist_goal_reached: 0.3       # [m] Threshold to consider the goal reached

  planner_type: 1              # 0: RRT Connect, 1: RRT*, 2: PRM
  replanning_rate: 5.0         # [Hz] useless if 'enable_timer_collisions' is False
  
  odometry_topic: "/base_odom"

 
   
