# more on http://wiki.ros.org/navigation/Tutorials/RobotSetup

local_costmap:
  global_frame: world
  robot_base_frame: base
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.1
  
  plugins:
    - 
     name: obstacle_layer
     type: "costmap_2d::ObstacleLayer"  
    -
     name: inflation_layer
     type: "costmap_2d::InflationLayer"

  virtual_obstacles:
    observation_sources: laser_scan_sensor
    
  obstacle_layer:
    enabled: true
    observation_sources: laser_scan_sensor 
    laser_scan_sensor:
      data_type: 'LaserScan'
      topic: scan
      marking: true
      clearing: true
      min_obstacle_height: -100.0
      max_obstacle_height: 100.0
      observation_persistence: 0.4
      inf_is_valid: true   

  inflation_layer:
    enabled: true
    inflation_radius: 0.1
    observation_sources: laser_scan_sensor
